[package]
name = "neural-net-fra"
version = "0.1.0"
edition = "2021"

[lib]
name = "nn_lib"
path = "src/lib.rs"

[dependencies]
fastrand = "1.7.0"
macroquad = "0.3.15"
# wasm-bindgen = "0.2.79"
# sapp-jsutils = "0.1.5"
